#!/system/bin/sh

 #r_name=$(echo $file | busybox sed 's!.*\/!!' | busybox awk -F"-|_|[+]|[.]|[{]|[(]" '{ print $1 }')

 r="$(busybox basename $file)"
 r_name=${r%.*}

 if [ -f ./"$file" ]; then
if [ -z "$(busybox hexdump -C -n 4 ./"$file" | grep '3a ff 26 ed')" ]; then
echo
echo ".....Konvertieren..."
echo
img2simg ./"$file" ./"$r_name".sparse.img 2> /dev/nul
 if [ $(echo $?) -eq 0 ]; then
echo
echo ".....Sparse-Image erhalten: \""$r_name".sparse.img\"!"
echo
 else
echo
echo ".....Konvertierungsfehler!"
echo
fi
else
echo
echo ".....Image ist schon sparse."
echo
fi
else
echo
echo ".....Kein "$file" Image im Ordner vorhanden."
echo
fi


