#!/system/bin/sh

#loop=$(busybox mount | grep "$file" | cut -d" " -f1)

loop=$(busybox mount | cut -d" " -f1,3 | grep "$file$" | cut -d" " -f1)
loop_d=$(busybox mount | cut -d" " -f3 | grep "$file$")
echo
echo ".....$file aushängen..."
echo
if [ ! -z "$loop_d" ]; then


 pid_term="$(cat /proc/$$/status | busybox awk '/^PPid:/ { print $2 }')"
 fuser -vm "$loop_d" &> /data/local/binary/fuser.txt
 
 check_pid="$(busybox cat /data/local/binary/fuser.txt | busybox grep -o "$pid_term")"
 if [ -z "$check_pid" ]; then

 fuser -skm "$loop_d"
 busybox umount "$loop_d"
if [ "$?" -eq 0 ]; then
losetup -d "$loop" 2> /dev/null
busybox rm -rf "$loop_d"

echo ".....Erfolgreich ausgehängt: $loop_d"
echo
else
echo
echo ".....Unmount-Fehler!"
fi
else
echo
echo ".....Unmount-Fehler!"
echo
#echo ".....Ordner zunächst im Terminal beenden: $loop_d"
echo ".....UKA beenden (Punkt 14), gebe ein: cd, drücke \"Eingabe\", UKA starten und erneut aushängen."
echo
fi
else
echo
echo ".....Ordner ist nicht gemountet!"
echo
fi

 busybox rm -f /data/local/binary/fuser.txt