#!/system/bin/sh

clear

size_output_sparse()
{
 if [ -s "$outdir"/"$pack_d".new.img ]; then
 echo
 echo ".....Erfolgreich erstellt "$pack_d".new.img!"
 echo
 size_out="$(busybox hexdump -C -n 50 "$outdir"/"$pack_d".new.img | busybox awk '{if($1==00000000) {b="0x"$17$16$15$14}} {if($1==00000010) {a="0x"$5$4$3$2}}
END {print a*b}')"
 busybox dd if="$outdir"/"$pack_d".new.img of="$pack_d".tmp.img bs=65536 count=1 &> /dev/null
busybox dd if="$pack_d".tmp.img of="$pack_d".size.img bs=40 skip=1 &> /dev/null
size_free="$(busybox expr "$(tune2fs -l "$pack_d".size.img | busybox awk '/Free blocks:/ { print $3 }')" \* 4096 / 1024 / 1024)"
 busybox rm -f "$pack_d".tmp.img "$pack_d".size.img
 echo "$size_out" > "$config"/"$pack_d"_size_out.txt
if [ "$check_dat" != "222" ]; then
 echo ".....Größe raw == $size_out Byte"
 echo ".....Freier Platz: $size_free MB"
 echo
fi
fi
 unset check_dat
 return
}


 baze_dir=/data/local/UnpackerSystem
 dir_avb=/data/local/UnpackerSystem/config/"$pack_d"
 img_name=$(cat "$dir_avb"/"$pack_d"*_name.txt)
 
 config="config/$pack_d"

 . /data/local/binary/perm_fs

 
 size_obraz="$(cat "$dir_avb"/"$pack_d"_size.txt)"
 if [ -s "$dir_avb"/"$pack_d"_avb.img ]; then
 #size_avb="$(avbtool add_hashtree_footer --partition_size "$size_obraz" --do_not_generate_fec --calc_max_image_size)"
 part_name="$(cat "$dir_avb"/"$pack_d"_part_name.txt)"
 fi

 cd /data/local/UnpackerSystem
 sed -i '/^$/d' "$config"/"$pack_d"_fs_config 2> /dev/null
 #pack_d="$pack_d"


my_sparse()
{
if [ -f ./"$pack_d".new.img ]; then
if [ -z "$(busybox hexdump -C -n 4 ./"$pack_d".new.img | busybox grep '3a ff 26 ed')" ]; then
  #. ${dir}/cap_pak
echo
echo ".....Конвертация в sparse..."
echo
img2simg ./"$pack_d".new.img ./"$pack_d".sparse.img 2> /dev/nul
            if [ $(echo $?) -eq 0 ]; then
            busybox rm -f ./"$pack_d".new.img
            busybox mv ./"$pack_d".sparse.img ./"$pack_d".new.img
busybox rm -f ./file_contexts ./fs_config
            fi
echo ".....Sparse-Image erhalten: \""$pack_d".new.img\"!"
else
echo
echo ".....Das Bild ist schon spärlich."
echo
fi
else
echo
echo ".....Kein Image im Ordner "$pack_d.new.img"."
echo
fi
}

my_pack(){
echo
echo ".....Wir sammeln mit einem Dritten file_contexts…"
cp ./"$config"/"$pack_d"*_fs_config ./fs_config
if [ -f ./file_contexts -a -f ./fs_config ]; then
echo
echo ".....Image erstellen "$pack_d".new.img…"
echo
if [ "$size" = "111" ]; then
 
 if [ -f ./"$config"/"$pack_d"*_avb.img ]; then

 size_avb="$(avbtool add_hashtree_footer --partition_size "$r_size" --do_not_generate_fec --calc_max_image_size)"

 chmod 755 ./"$config"/"$pack_d"_pack_avb_sparse.sh && . ./"$config"/"$pack_d"_pack_avb_sparse.sh
 if [ $(echo $?) -eq 0 ]; then
 echo
 echo ".....AVB-Struktur erstellen…"
 
 avbtool add_hashtree_footer --image "$outdir"/"$pack_d".new.img --partition_size "$r_size" --partition_name "$part_name" --do_not_generate_fec

 if [ $(echo $?) -eq 0 ]; then
 #echo
 #echo ".....Erfolgreich erstellt "$pack_d".new.img!"
 #echo
 size_output_sparse
 else
 echo
 echo ".....Fehler: Fehler beim Erstellen der AVB-Struktur!"
 echo
 fi
 else
 echo
 echo ".....Fehler: Fehler beim erstellen!"
 echo
 fi

 else
 chmod 755 ./"$config"/"$pack_d"_gsize.sh && . ./"$config"/"$pack_d"_gsize.sh
 if [ $(echo $?) -eq 0 ]; then
 #echo
 #echo ".....
Erfolgreich erstellt "$pack_d".new.img!"
 #echo
 size_output_sparse
 else
 echo
 echo ".....Fehler: Fehler beim erstellen"
 echo
 fi
 fi
 else
 if [ -f ./"$config"/"$pack_d"*_avb.img ]; then

 size_avb="$(avbtool add_hashtree_footer --partition_size "$size_obraz" --do_not_generate_fec --calc_max_image_size)"


 chmod 755 ./"$config"/"$pack_d"_pack_avb_sparse.sh && . ./"$config"/"$pack_d"_pack_avb_sparse.sh
 if [ $(echo $?) -eq 0 ]; then
  echo
 echo ".....AVB-Struktur erstellen…"
 
  avbtool add_hashtree_footer --image "$outdir"/"$pack_d".new.img --partition_size "$size_obraz" --partition_name "$part_name" --do_not_generate_fec
 if [ $(echo $?) -eq 0 ]; then
 #echo
 #echo ".....Erfolgreich erstellt "$pack_d".new.img!"
 #echo
 size_output_sparse
 else
 echo
 echo ".....Fehler: Fehler beim Erstellen der AVB-Struktur!"
 echo
 fi
 else
 if [ $(echo $?) -eq 0 ]; then
 #echo
 #echo ".....Erfolgreich erstellt "$pack_d".new.img!"
 #echo
 size_output_sparse
 else
 echo
 echo ".....Fehler: Fehler beim Erstellen!"
 echo
 fi
 fi
 else
 chmod 755 ./"$config"/"$pack_d"*_pack_sparse.sh && . ./"$config"/"$pack_d"*_pack_sparse.sh
 if [ $(echo $?) -eq 0 ]; then
 #echo
 #echo ".....Erfolgreich erstellt "$pack_d".new.img!"
 #echo
 size_output_sparse
 else
 echo
 echo ".....Fehler: Fehler beim Erstellen!"
 echo
 fi
 fi
 fi
 else
echo
echo ".....Fehlende Konfigurationsdateien im Ordner: /data/local/UnpackerSystem/config."
echo
fi
}

 if [ -d ./"$pack_d" -a -f ./"$config"/"$pack_d"*_pack_sparse.sh ]; then

 if [ ! -f ./file_contexts ]; then
echo
echo ".....Dateikontexte von Drittanbietern nicht gefunden, sammeln mit erhalten beim Entpacken des Images..."
cp ./"$config"/"$pack_d"*_fs_config ./fs_config
cp ./"$config"/"$pack_d"*_file_contexts ./file_contexts
if [ -f ./file_contexts -a -f ./fs_config ]; then
echo
echo ".....Image erstellen "$pack_d".new.img…"
echo
 if [ "$size" = "111" ]; then
 
 if [ -f ./"$config"/"$pack_d"*_avb.img ]; then

 size_avb="$(avbtool add_hashtree_footer --partition_size "$r_size" --do_not_generate_fec --calc_max_image_size)"

 chmod 755 ./"$config"/"$pack_d"_pack_avb_sparse.sh && . ./"$config"/"$pack_d"_pack_avb_sparse.sh
 if [ $(echo $?) -eq 0 ]; then
 echo
 echo ".....AVB-Struktur erstellen…"
 
 avbtool add_hashtree_footer --image "$outdir"/"$pack_d".new.img --partition_size "$r_size" --partition_name "$part_name" --do_not_generate_fec

 if [ $(echo $?) -eq 0 ]; then
 #echo
 #echo ".....Erfolgreich erstellt "$pack_d".new.img!"
 #echo
 size_output_sparse
 else
 echo
 echo ".....Fehler: Fehler beim Erstellen der AVB-Struktur!"
 echo
 fi
 else
 echo
 echo ".....Fehler: Fehler beim Erstellen"
 echo
 fi

 else
 chmod 755 ./"$config"/"$pack_d"_gsize.sh && . ./"$config"/"$pack_d"_gsize.sh
 if [ $(echo $?) -eq 0 ]; then
 #echo
 #echo ".....Erfolgreich erstellt "$pack_d".new.img!"
 #echo
 size_output_sparse
 else
 echo
 echo ".....Fehler: Fehler beim Erstellen!"
 echo
 fi
 fi
 else
 if [ -f ./"$config"/"$pack_d"*_avb.img ]; then

 size_avb="$(avbtool add_hashtree_footer --partition_size "$size_obraz" --do_not_generate_fec --calc_max_image_size)"


 chmod 755 ./"$config"/"$pack_d"_pack_avb_sparse.sh && . ./"$config"/"$pack_d"_pack_avb_sparse.sh
 if [ $(echo $?) -eq 0 ]; then
  echo
 echo ".....AVB-Struktur erstellen…"
 
  avbtool add_hashtree_footer --image "$outdir"/"$pack_d".new.img --partition_size "$size_obraz" --partition_name "$part_name" --do_not_generate_fec
 if [ $(echo $?) -eq 0 ]; then
 #echo
 #echo ".....Erfolgreich erstellt "$pack_d".new.img!"
 #echo
 size_output_sparse
 else
 echo
 echo ".....Fehler: Fehler beim Erstellen der AVB-Struktur!"
 echo
 fi
 else
 if [ $(echo $?) -eq 0 ]; then
 #echo
 #echo ".....Erfolgreich erstellt "$pack_d".new.img!"
 #echo
 size_output_sparse
 else
 echo
 echo ".....Fehler: Fehler beim Erstellen!"
 echo
 fi
 fi
 else
 chmod 755 ./"$config"/"$pack_d"*_pack_sparse.sh && . ./"$config"/"$pack_d"*_pack_sparse.sh
 if [ $(echo $?) -eq 0 ]; then
 #echo
 #echo ".....Erfolgreich erstellt "$pack_d".new.img!"
 #echo
 size_output_sparse
 else
 echo
 echo ".....Fehler: Fehler beim Erstellen!"
 echo
 fi
 fi
 fi
else
echo
echo ".....Fehlende Konfigurationsdateien im Ordner: /data/local/UnpackerSystem/config."
echo
fi
else
my_pack
fi
else
echo
echo ".....Es gibt keinen Ordner \"$pack_d"\", um das Image oder die Datei *_pack_sparse.sh zu erstellen."
echo
fi
rm -f ./file_contexts ./fs_config

